### ISSUE TITLE
எழுத்துபிழை திருத்துக

### ISSUE THREAD

**Issue by arulconsultant** [solladal/wordle-tamil#1]
வாய்ப்புகள் என ஒரு சொல் வரின், முடிந்தது என வரி முடியலாகா. முடிந்தன என கூறல் வேண்டும்

**Comment by arulconsultant** [comment]
//மன்னிக்கவும், வாய்ப்புகள் முடிந்தது!!//

**Comment by solladal** [comment]
நன்றி, பிழை திருத்தப்பட்டது

Thanks,
Wordle-Tamil
